name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          COMMIT_BY_ME: "True"
          SHOW_COMMIT: "False"
          SHOW_SHORT_INFO: "False"
          SYMBOL_VERSION: 2
          LOCALE: "en"
